#!/bin/bash

declare -a args

for arg in "$@" ;do
	if [[ "$arg" = "cwappy" ]] ;then
		make -C cwappy
		retval=$?
		[[ $retval -eq 0 ]] || exit $retval
	else
		args+=("$arg")
	fi
done

[[ -f temp.ino ]] && rm temp.ino

for file in *.ino *.c ; do
	echo "#line 1 \"$file\"" >> temp.ino
	cat "$file" >> temp.ino
	mv "$file" "$file"_
done

if [[ ${#args[@]} -eq 0 ]] ;then
	make -fMakefile_ all
else
	make -fMakefile_ "${args[@]}"
fi
retval=$?

rm temp.ino

for file in *.ino_ *.c_ ; do
	mv "$file" "${file%%_}"
done

exit $retval
