#!/bin/bash

[[ -f temp.ino ]] && rm temp.ino

for file in *.ino *.c ; do
	echo "#line 1 \"$file\"" >> temp.ino
	cat "$file" >> temp.ino
	mv "$file" "$file"_
done

make -fMakefile_ "$@"
retval=$?

rm temp.ino

for file in *.ino_ *.c_ ; do
	mv "$file" "${file%%_}"
done

exit $retval
