#!/bin/bash

for file in *.ino *.c ; do
	mv "$file" "$file"_
done

cat *.ino_ > temp.ino

if [[ $# -eq 0 ]] ;then
	make -fMakefile_ all
else
	make -fMakefile_ "$@"
fi
retval=$?

rm temp.ino

for file in *.ino_ *.c_ ; do
	mv "$file" "${file%%_}"
done

exit $retval
